// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1jWPDZ7GRTWnAB40tIbA8Wnp8Tv0-wxk',
    appId: '1:862047552501:web:027f645edd5305058bd6bc',
    messagingSenderId: '862047552501',
    projectId: 'animewatch-production',
    authDomain: 'animewatch-production.firebaseapp.com',
    storageBucket: 'animewatch-production.firebasestorage.app',
    measurementId: 'G-WP24YWWDCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjE0b07hl_Q9acoNybMo9CRz0h3M6Yk3Y',
    appId: '1:862047552501:android:739105a6c08e76138bd6bc',
    messagingSenderId: '862047552501',
    projectId: 'animewatch-production',
    storageBucket: 'animewatch-production.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEJNrgN9onyEtuuhie-M2uC9oUnqf-f9s',
    appId: '1:862047552501:ios:bd2c34053de5f1da8bd6bc',
    messagingSenderId: '862047552501',
    projectId: 'animewatch-production',
    storageBucket: 'animewatch-production.firebasestorage.app',
    iosBundleId: 'com.example.animevaultApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEJNrgN9onyEtuuhie-M2uC9oUnqf-f9s',
    appId: '1:862047552501:ios:bd2c34053de5f1da8bd6bc',
    messagingSenderId: '862047552501',
    projectId: 'animewatch-production',
    storageBucket: 'animewatch-production.firebasestorage.app',
    iosBundleId: 'com.example.animevaultApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1jWPDZ7GRTWnAB40tIbA8Wnp8Tv0-wxk',
    appId: '1:862047552501:web:f14ccfa84307fba48bd6bc',
    messagingSenderId: '862047552501',
    projectId: 'animewatch-production',
    authDomain: 'animewatch-production.firebaseapp.com',
    storageBucket: 'animewatch-production.firebasestorage.app',
    measurementId: 'G-L61DHH3X47',
  );
}
